apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    name: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      name: spring-petclinic-pod
  template:
    metadata:
      name: spring-petclinic-pod
      labels:
        name: spring-petclinic-pod
    spec:
      containers:
        - name:  spring-petclinic-container
          image: jnaidu023/petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  labels:
    name: spring-petclinic-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32011
  selector:
    name: spring-petclinic-pod
  type: NodePort
